
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "craftista_rules.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'craftista-app'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - craftista
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: craftista-service
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http

      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

  craftista_rules.yml: |
    groups:
    - name: craftista.rules
      rules:
      - alert: CraftistaHighErrorRate
        expr: rate(http_requests_total{job="craftista-app",status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected for Craftista app"
          description: "Error rate is {{ $value }} errors per second"

      - alert: CraftistaHighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="craftista-app"}[5m])) > 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High response time for Craftista app"
          description: "95th percentile response time is {{ $value }} seconds"

      - alert: CraftistaPodCrashLooping
        expr: rate(kube_pod_container_status_restarts_total{namespace="craftista"}[15m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Craftista pod is crash looping"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting"
