
apiVersion: apps/v1
kind: Deployment
metadata:
  name: craftista-app
  namespace: craftista
  labels:
    app: craftista
spec:
  replicas: 3
  selector:
    matchLabels:
      app: craftista
  template:
    metadata:
      labels:
        app: craftista
    spec:
      containers:
      - name: craftista
        image: craftista:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: craftista-config
              key: API_URL
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: craftista-config
              key: APP_ENV
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: craftista-secrets
              key: db-password
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: craftista-secrets
              key: api-key
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
